# ----------------------------------------------------------------------------------------------------------------------
# GENERAL
# ----------------------------------------------------------------------------------------------------------------------
general:
  prefix: ii
  region: EastUS
  unique_id: i1r1
  use_legacy_naming: false
  tags:
    IngeniiApplication: Azure Data Platform
    IngeniiNotice: "This resource is managed using infrastructure as code approach. Please do not make any manual changes as they will be overwritten on the next infrastructure update."

# ----------------------------------------------------------------------------------------------------------------------
# MANAGEMENT
# ----------------------------------------------------------------------------------------------------------------------
management:
  user_groups:
    admins:
      display_name: admins
    engineers:
      display_name: engineers
    analysts:
      display_name: analysts
  resource_groups:
    infra:
      display_name: infra
      iam:
        role_assignments:
          - user_group_ref_key: admins
            role_definition_name: Owner
          - user_group_ref_key: engineers
            role_definition_name: Reader
          - user_group_ref_key: analysts
            role_definition_name: Reader
    data:
      display_name: data
      iam:
        role_assignments:
          - user_group_ref_key: admins
            role_definition_name: Owner
          - user_group_ref_key: engineers
            role_definition_name: Reader
          - user_group_ref_key: analysts
            role_definition_name: Reader
    security:
      display_name: security
      iam:
        role_assignments:
          - user_group_ref_key: admins
            role_definition_name: Owner
          - user_group_ref_key: engineers
            role_definition_name: Reader
          - user_group_ref_key: analysts
            role_definition_name: Reader
# ----------------------------------------------------------------------------------------------------------------------
# SECURITY
# ----------------------------------------------------------------------------------------------------------------------
security:
  config_registry:
    network:
      firewall:
        enabled: false
    iam:
      role_assignments:
        - user_group_ref_key: admins
          role_definition_name: "Key Vault Secrets Reader"

# ----------------------------------------------------------------------------------------------------------------------
# NETWORK
# ----------------------------------------------------------------------------------------------------------------------
network:
  firewall:
    enabled: false
    ip_access_list:
      - 151.251.5.72
  nat_gateway:
    enabled: true
  virtual_network:
    display_name: main
    address_space: 10.100.0.0/16

# ----------------------------------------------------------------------------------------------------------------------
# AUTOMATION
# ----------------------------------------------------------------------------------------------------------------------
automation:
  devops:
    project:
      name: Ingenii Data Platform
      description: Repositories and pipelines related to the data platform.
      features:
        - pipelines
        - repositories
        - artifacts
      version_control: "Git"
      visibility: "private"
      work_item_template: "Agile"
    repositories:
      - name: "data-engineering"
        import_url: "https://github.com/ingenii-solutions/azure-data-platform-data-engineering-example"
        pipeline:
          use_yml: True
          branch_name: "main"
          yml_path: "azure-pipelines.yml"
