# ----------------------------------------------------------------------------------------------------------------------
# GENERAL
# ----------------------------------------------------------------------------------------------------------------------
  general:
    prefix: adp
    region: EastUS
    unique_id: iii
    tags:
      Environment: Test
  
  # ----------------------------------------------------------------------------------------------------------------------
  # MANAGEMENT
  # ----------------------------------------------------------------------------------------------------------------------
  management:
    user_groups:
      admins:
        display_name: admins
      engineers:
        display_name: engineers
      analysts:
        display_name: analysts
  
  # ----------------------------------------------------------------------------------------------------------------------
  # NETWORK
  # ----------------------------------------------------------------------------------------------------------------------
  network:
    firewall:
      enabled: false
      ip_access_list:
        - 151.251.5.72
    nat_gateway:
      enabled: true
    virtual_network:
      display_name: main
      address_space: 10.110.0.0/16
    
  # ----------------------------------------------------------------------------------------------------------------------
  # SECURITY
  # ----------------------------------------------------------------------------------------------------------------------
  security:
    credentials_store:
      network:
        firewall:
          enabled: false
  
  # ----------------------------------------------------------------------------------------------------------------------
  # ANALYTICS SERVICES
  # ----------------------------------------------------------------------------------------------------------------------
  analytics_services:
    databricks:
      workspaces:
        engineering:
          clusters:
            default:
              spark_version: "8.4.x-scala2.12"
              node_type_id: "Standard_F4s"
              autotermination_minutes: 15
        analytics:
          clusters:
            default:
              spark_version: "8.4.x-scala2.12"
              node_type_id: "Standard_F4s"
              auto_scale_min_workers: 1
              auto_scale_max_workers: 4
              autotermination_minutes: 15
              libraries:
                pypi:
                  - package: dbt