name: Publish Docker IaC Runtime Image
on:
  push:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------
      - name: Check out the repo
        uses: actions/checkout@v2
      # ----------------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.INGENII_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.INGENII_DOCKER_HUB_PASSWORD }}
      # ----------------------------------------
      - name: Build the image
        run: make build-docker-image
      # ----------------------------------------
      - name: Publish 'latest-dev' tag
        if: github.ref != 'refs/heads/main' && github.event_name != 'release'
        run: make publish-docker-image DOCKER_IMAGE_TAG=latest-dev
      # ----------------------------------------
      - name: Publish 'latest' tag
        if: github.ref == 'refs/heads/main' || github.event_name == 'release'
        run: make publish-docker-image DOCKER_IMAGE_TAG=latest
      # ----------------------------------------
      - name: Get a release version
        if: github.event_name == 'release'
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      # ------------------------------------------
      - name: Publish specific version
        if: github.event_name == 'release'
        run: make publish-docker-image DOCKER_IMAGE_TAG=${{ steps.tag_name.outputs.SOURCE_TAG }}