name: Publish Docker IaC Runtime Image
on:
  push:
  release:
    types: [published]
env:
  IMAGE_NAME: "ingeniisolutions/azure-data-platform-iac-runtime"
  PLATFORMS: "linux/amd64,linux/arm64"
jobs:
  push_to_registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------
      - name: Check out the repo
        uses: actions/checkout@v2
      # ----------------------------------------
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # ----------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # ----------------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.INGENII_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.INGENII_DOCKER_HUB_PASSWORD }}
      # ----------------------------------------
      - name: Publish 'latest-dev'
        if: github.ref != 'refs/heads/main' && github.event_name != 'release'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            "${{ env.IMAGE_NAME }}:latest-dev"
      # ----------------------------------------
      - name: Publish 'latest'
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            "${{ env.IMAGE_NAME }}:latest"
      # ----------------------------------------
      - name: Get a release version
        if: github.event_name == 'release'
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      # ------------------------------------------
      - name: Publish release version
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            "${{ env.IMAGE_NAME }}:${{ steps.tag_name.outputs.SOURCE_TAG }}"
